// This file is automatically generated. DO NOT EDIT.

class AppConstants {
  static const String app_name = 'eShop Multivendor Seller';
  static const String packageName = 'wrteam.seller.multivendor';
  static const String iosPackage = 'eshop.seller.multivendor';
  //please add your panel's API base URL here (you can find from settings->client APIs)
  static const String baseUrl = 'https://mntom.online/seller/app/v1/api/';
  static const String chatBaseUrl = 'https://mntom.online/seller/app/v1/Chat_Api/';
  static const String defaultLanguageCode = 'en';
  static const String defaultLanguageName = "English";

  // ── Multilingual dynamic content (AR / EN / HI / UR) ──────────────
  // Language-specific product/content fields are entered per language.
  // Order controls the tab order; keep the default language available.
  // Codes must match the backend `languages`.code column.
  static const List<Map<String, String>> contentLanguages = [
    {'code': 'en', 'name': 'English'},
    {'code': 'ar', 'name': 'العربية'},
    {'code': 'hi', 'name': 'हिन्दी'},
    {'code': 'ur', 'name': 'اردو'},
  ];
  // RTL languages among the content languages (for field text direction).
  static const List<String> rtlLanguageCodes = ['ar', 'ur'];

  // ── Wafeq e-Invoicing (ZATCA) ─────────────────────────────────────
  static const String wafeqApiKey = 'RlNRjHLa.anZilf3YhSdcsRzZ3S3720Be0SHXrc9C';
  static const String wafeqBaseUrl = 'https://api.wafeq.com/v1/';
  // Chart of Accounts: Sales account ID (fetched from Wafeq API)
  static const String wafeqSalesAccountId = 'acc_DZWQpGrsJ2N9y6Jky6633G';
  // VAT tax ID in Wafeq (15% Saudi VAT) — found in Wafeq → Settings → Taxes
  static const String wafeqVatTaxId = 'tax_NaNjXPpwbUoVDGhwgvEjFj';
}
